backend:
  name: git-gateway
  branch: main

collections:
  - name: "projects"
    label: "Projects"
    files:
      - file: "projects.json"
        label: "Projects List"
        name: "projects_list"
        format: "json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Tags", name: "tags", widget: "list" }
              - { label: "PDF File", name: "file", widget: "string", hint: "Dropbox link ending with ?dl=1" }