backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"    
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    files:
      - file: "projects.json"
        label: "Projects List"
        name: "projects_list"
        format: "json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Tags", name: "tags", widget: "relation", collection: "tags", search_fields: ["title"], display_fields: ["title"], value_field: "title", multiple: true }
              - { label: "PDF File", name: "file", widget: "string", hint: "Dropbox link ending with ?dl=1" }
  - label: "Tags"
    name: "tags"
    folder: "tags"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
    - { label: "Title", name: "title", widget: "string" }
