backend:
  name: git-gateway
  branch: main  

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    description: "Upload project PDFs with metadata"
    file: "projects.json"   # single JSON file
    format: "json"
    fields:
      - {label: "Projects", name: "projects", widget: "list", fields: [
          {label: "Title", name: "title", widget: "string"},
          {label: "Tags", name: "tags", widget: "list"},
          {label: "PDF File", name: "file", widget: "string", hint: "Paste Dropbox share link ending with ?dl=1"}
        ]}